/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "super.admins.index": [],
    "super.admins.store": [],
    "super.admins.edit": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "super.admins.update": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "super.admins.destroy": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "super.admins.deactivate": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "super.admins.reactivate": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "super.admins.two-factor.reset": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "super.admins.password-link": [
        {
            "name": "admin",
            "required": true,
            "binding": "id"
        }
    ],
    "super.profile.show": [],
    "super.profile.update": [],
    "super.profile.password": [],
    "super.profile.sessions.destroy_others": [],
    "super.profile.sessions.destroy": [
        {
            "name": "ref",
            "required": true
        }
    ],
    "super.password.set": [
        {
            "name": "token",
            "required": true
        }
    ],
    "super.password.store": [],
    "super.login": [],
    "super.login.store": [],
    "super.two-factor.challenge": [],
    "super.two-factor.challenge.store": [],
    "super.logout": [],
    "super.two-factor.show": [],
    "super.two-factor.store": [],
    "super.two-factor.confirm": [],
    "super.two-factor.recovery-codes": [],
    "super.two-factor.destroy": [],
    "super.dashboard": [],
    "super.billing.index": [],
    "super.billing.subscriptions.index": [],
    "super.billing.subscriptions.plan": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.subscriptions.end-trial": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.subscriptions.dun": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.subscriptions.suspend": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.subscriptions.reactivate": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.subscriptions.cancel": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.invoices.index": [],
    "super.billing.invoices.store": [],
    "super.billing.invoices.issue": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.invoices.void": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.invoices.pay": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.invoices.print": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.invoices.pdf": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.payments.index": [],
    "super.billing.dunning.index": [],
    "super.billing.dunning.run": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.billing.export": [
        {
            "name": "kind",
            "required": true
        }
    ],
    "super.catalog.index": [],
    "super.catalog.imports.index": [],
    "super.catalog.imports.store": [],
    "super.catalog.imports.show": [
        {
            "name": "job",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.catalog.imports.dry-run": [
        {
            "name": "job",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.catalog.imports.apply": [
        {
            "name": "job",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.catalog.imports.destroy": [
        {
            "name": "job",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.catalog.index.rebuild": [],
    "super.catalog.reconcile.run": [],
    "super.catalog.reconciliation.show": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "super.catalog.reconciliation.notify": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "super.catalog.promotions.index": [],
    "super.catalog.promotions.tenants": [],
    "super.catalog.promotions.show": [
        {
            "name": "promotion",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.catalog.promotions.approve": [
        {
            "name": "promotion",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.catalog.promotions.reject": [
        {
            "name": "promotion",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.catalog.show": [
        {
            "name": "kind",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "super.catalog.active": [
        {
            "name": "kind",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "super.catalog.information": [
        {
            "name": "id",
            "required": true
        }
    ],
    "super.catalog.icd10.aliases": [
        {
            "name": "id",
            "required": true
        }
    ],
    "super.notifications.index": [],
    "super.notifications.update": [],
    "super.notifications.templates.reset": [
        {
            "name": "key",
            "required": true
        }
    ],
    "super.notifications.templates.preview": [],
    "super.notifications.test": [],
    "super.plans.index": [],
    "super.plans.create": [],
    "super.plans.store": [],
    "super.plans.edit": [
        {
            "name": "plan",
            "required": true,
            "binding": "code"
        }
    ],
    "super.plans.update": [
        {
            "name": "plan",
            "required": true,
            "binding": "code"
        }
    ],
    "super.plans.destroy": [
        {
            "name": "plan",
            "required": true,
            "binding": "code"
        }
    ],
    "super.plans.clone": [
        {
            "name": "plan",
            "required": true,
            "binding": "code"
        }
    ],
    "super.ping": [],
    "super.usage.index": [],
    "super.usage.export": [],
    "super.usage.show": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.audit.index": [],
    "super.audit.export": [],
    "super.catalog.review": [],
    "super.catalog.reconciliation.index": [],
    "super.catalog.reconciliation.resolve": [
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "super.settings.index": [],
    "super.settings.update": [
        {
            "name": "key",
            "required": true
        }
    ],
    "super.tenants.index": [],
    "super.tenants.create": [],
    "super.tenants.store": [],
    "super.tenants.slug-check": [],
    "super.tenants.show": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.edit": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.update": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.destroy": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.slug": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.deletion.prepare": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.suspend": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.reactivate": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.cancel": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.plan": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.features": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.limits": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.invoices.store": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.invoices.issue": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.invoices.void": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.invoices.pay": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.impersonate": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.staff.store": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.staff.password": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "user",
            "required": true
        }
    ],
    "super.tenants.staff.status": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "user",
            "required": true
        }
    ],
    "super.tenants.backups.store": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.exports.store": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.archives.download": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "backup",
            "required": true,
            "binding": "id"
        }
    ],
    "super.tenants.archives.restore": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "backup",
            "required": true,
            "binding": "id"
        }
    ],
    "super.tenants.domains.store": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "super.tenants.domains.verify": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "domain",
            "required": true,
            "binding": "id"
        }
    ],
    "super.tenants.domains.primary": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "domain",
            "required": true,
            "binding": "id"
        }
    ],
    "super.tenants.domains.destroy": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "domain",
            "required": true,
            "binding": "id"
        }
    ],
    "central.billing.invoice": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "central.billing.pay": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "central.billing.callback": [
        {
            "name": "gateway",
            "required": true
        }
    ],
    "central.home": [],
    "central.pricing": [],
    "central.changelog": [],
    "central.docs.index": [],
    "central.docs.show": [
        {
            "name": "section",
            "required": true
        }
    ],
    "central.locale": [],
    "central.onboarding.create": [],
    "central.onboarding.store": [],
    "central.onboarding.done": [
        {
            "name": "tenant",
            "required": true,
            "binding": "public_id"
        }
    ],
    "central.www": [
        {
            "name": "path",
            "required": false
        }
    ],
    "api.billing.webhook": [
        {
            "name": "gateway",
            "required": true
        }
    ],
    "api.booking.public.store": [],
    "api.catalog.drugs": [],
    "api.catalog.icd10": [],
    "api.catalog.generics": [],
    "api.catalog.vocabulary": [],
    "api.notifications.push.key": [],
    "api.notifications.push.subscribe": [],
    "api.notifications.push.unsubscribe": [],
    "api.notifications.dlr": [
        {
            "name": "gateway",
            "required": true,
            "binding": "id"
        }
    ],
    "api.patients.search": [],
    "api.patients.recent": [],
    "api.patients.by_mobile": [
        {
            "name": "mobile",
            "required": true
        }
    ],
    "api.patients.summary": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.queue.sessions.state": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.queue.display.tiles": [
        {
            "name": "branch",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.reception.devices.register": [],
    "api.reception.bootstrap": [],
    "api.reception.board": [],
    "api.reception.print-templates": [],
    "api.reception.patients.recent": [],
    "api.reception.patients.lookup": [],
    "api.reception.sync.conflicts": [],
    "api.reception.blocks.index": [],
    "api.reception.blocks.lease": [],
    "api.reception.blocks.release": [
        {
            "name": "block",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.reception.blocks.revoke": [
        {
            "name": "block",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.reception.devices.revoke": [
        {
            "name": "device",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.reception.sync": [],
    "api.reception.sync.resolve": [],
    "api.reports.dashboard": [],
    "api.scheduling.availability": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "api.sessions.show": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.capacity": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.serials.store": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.call-next": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.start": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.pause": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.resume": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.close": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.cancel": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.delay": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.extend": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.transfer": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.pools.release-online": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.sessions.pools.split": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.check-in": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.call": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.start": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.complete": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.skip": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.return": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.no-show": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.reinstate": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.cancel": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.postpone": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.transfer": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.reorder": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.serials.priority": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "api.telemedicine.webhook": [],
    "api.tenancy.ping": [],
    "panel.login": [],
    "panel.login.store": [],
    "panel.password.request": [],
    "panel.password.email": [],
    "panel.password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "panel.password.store": [],
    "panel.locale": [],
    "panel.logout": [],
    "panel.branch.switch": [],
    "panel.dashboard": [],
    "panel.billing.index": [],
    "panel.billing.invoices.store": [],
    "panel.billing.invoices.show": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.invoices.issue": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.invoices.void": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.invoices.payments.store": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.invoices.discounts.store": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.invoices.coupon": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.invoices.refunds.store": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.invoices.refunds.process": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "refund",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.billing.invoices.refunds.eligibility": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.invoices.print": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.invoices.receipt": [
        {
            "name": "invoice",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "payment",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.patients.dues": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.billing.coupons.index": [],
    "panel.billing.coupons.store": [],
    "panel.billing.coupons.update": [
        {
            "name": "coupon",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.billing.coupons.destroy": [
        {
            "name": "coupon",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.billing.shift.index": [],
    "panel.billing.shift.open": [],
    "panel.billing.shift.close": [
        {
            "name": "shift",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.billing.revenue_shares.index": [],
    "panel.billing.revenue_shares.store": [],
    "panel.billing.revenue_shares.update": [
        {
            "name": "share",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.billing.revenue_shares.destroy": [
        {
            "name": "share",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.billing.reports.index": [],
    "panel.billing.reports.export": [],
    "panel.catalog.custom-brands.index": [],
    "panel.catalog.custom-brands.store": [],
    "panel.catalog.custom-brands.update": [
        {
            "name": "customBrand",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.catalog.custom-brands.destroy": [
        {
            "name": "customBrand",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.clinic.branches.index": [],
    "panel.clinic.branches.create": [],
    "panel.clinic.branches.store": [],
    "panel.clinic.branches.edit": [
        {
            "name": "branch",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.branches.update": [
        {
            "name": "branch",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.branches.status": [
        {
            "name": "branch",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.branches.main": [
        {
            "name": "branch",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.departments.index": [],
    "panel.clinic.departments.store": [],
    "panel.clinic.departments.update": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.clinic.departments.destroy": [
        {
            "name": "department",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.clinic.specialties.index": [],
    "panel.clinic.specialties.store": [],
    "panel.clinic.specialties.update": [
        {
            "name": "specialty",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.clinic.specialties.destroy": [
        {
            "name": "specialty",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.clinic.staff.index": [],
    "panel.clinic.staff.create": [],
    "panel.clinic.staff.store": [],
    "panel.clinic.staff.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.staff.update": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.staff.status": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.staff.password_reset": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.staff.sessions.index": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.staff.sessions.destroy_others": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.staff.sessions.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "ref",
            "required": true
        }
    ],
    "panel.clinic.doctors.index": [],
    "panel.clinic.doctors.create": [],
    "panel.clinic.doctors.store": [],
    "panel.clinic.doctors.edit": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.doctors.update": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.doctors.photo.store": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.doctors.photo.show": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.doctors.pad.edit": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.doctors.pad.update": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.doctors.pad.asset": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.doctors.pad.asset.destroy": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.doctors.pad.asset.show": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "kind",
            "required": true
        }
    ],
    "panel.clinic.doctors.pad.test_print": [
        {
            "name": "doctor",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.clinic.holidays.index": [],
    "panel.clinic.holidays.store": [],
    "panel.clinic.holidays.destroy": [
        {
            "name": "holiday",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.clinic.leaves.index": [],
    "panel.clinic.leaves.store": [],
    "panel.clinic.leaves.destroy": [
        {
            "name": "leave",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.clinic.settings.index": [],
    "panel.clinic.settings.update": [],
    "panel.clinic.branding.update": [],
    "panel.notifications.index": [],
    "panel.notifications.show": [
        {
            "name": "notification",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.notifications.retry": [
        {
            "name": "notification",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.notifications.templates.index": [],
    "panel.notifications.templates.store": [],
    "panel.notifications.templates.preview": [],
    "panel.notifications.templates.destroy": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.notifications.gateways.index": [],
    "panel.notifications.gateways.store": [],
    "panel.notifications.gateways.update": [
        {
            "name": "gateway",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.notifications.gateways.destroy": [
        {
            "name": "gateway",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.notifications.gateways.test": [
        {
            "name": "gateway",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.notifications.push.index": [],
    "panel.notifications.push.destroy": [
        {
            "name": "subscription",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.patients.index": [],
    "panel.patients.create": [],
    "panel.patients.store": [],
    "panel.patients.show": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.edit": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.update": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.dependents.store": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.merge": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.timeline": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.vitals_trend": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.allergies.index": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.allergies.store": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.allergies.update": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "allergy",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.patients.allergies.destroy": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "allergy",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.patients.conditions.index": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.conditions.store": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.conditions.update": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "condition",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.patients.conditions.destroy": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "condition",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.patients.medications.index": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.medications.store": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.medications.update": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "medication",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.patients.medications.destroy": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "medication",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.patients.documents.store": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.patients.documents.show": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "document",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.patients.consents.store": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescriptions.index": [],
    "panel.prescription.visits.start": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.visits.store": [
        {
            "name": "patient",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.visits.show": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.visits.update": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.visits.close": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.writer": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.vitals.index": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.vitals.store": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.vitals.update": [
        {
            "name": "vital",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.drafts.store": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.ai.summary": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.ai.differentials": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.ai.decide": [
        {
            "name": "suggestion",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.prescriptions.show": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.versions": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.draft": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.destroy": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.check": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.issue": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.amend": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.void": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.apply-template": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.prescriptions.handwriting": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.drawing": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.prescriptions.send": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.print": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.pharmacy": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.pdf": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.pdf.regenerate": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.prescription.files": [
        {
            "name": "prescription",
            "required": true,
            "binding": "public_id"
        },
        {
            "name": "file",
            "required": true
        }
    ],
    "panel.prescription.templates.index": [],
    "panel.prescription.templates.store": [],
    "panel.prescription.templates.show": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.templates.update": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.templates.destroy": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.snippets.index": [],
    "panel.prescription.snippets.store": [],
    "panel.prescription.snippets.update": [
        {
            "name": "snippet",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.snippets.destroy": [
        {
            "name": "snippet",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.investigations.index": [],
    "panel.prescription.investigations.store": [],
    "panel.prescription.investigations.update": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.investigations.destroy": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.centres.index": [],
    "panel.prescription.centres.store": [],
    "panel.prescription.centres.update": [
        {
            "name": "centre",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.centres.destroy": [
        {
            "name": "centre",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.favourites.index": [],
    "panel.prescription.favourites.store": [],
    "panel.prescription.favourites.update": [
        {
            "name": "favourite",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.favourites.destroy": [
        {
            "name": "favourite",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.prescription.favourites.top-drugs": [],
    "panel.prescription.search.drugs": [],
    "panel.prescription.search.icd": [],
    "panel.prescription.search.investigations": [],
    "panel.prescription.search.doctors": [],
    "panel.prescription.help.shorthand": [],
    "panel.queue.index": [],
    "panel.queue.today": [],
    "panel.queue.today.data": [],
    "panel.queue.doctor": [],
    "panel.reception.board": [],
    "panel.reception.board.data": [],
    "panel.reception.shift": [],
    "panel.reception.devices.index": [],
    "panel.reception.devices.revoke": [
        {
            "name": "device",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.reception.kiosk_url": [],
    "panel.reception.print_templates": [],
    "panel.reception.patients.lookup": [],
    "panel.reception.bookings.store": [],
    "panel.reception.appointments.collect": [
        {
            "name": "appointment",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.reception.appointments.cancel": [
        {
            "name": "appointment",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.reception.appointments.reschedule": [
        {
            "name": "appointment",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.reception.vitals.open": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.reception.vitals.edit": [
        {
            "name": "visit",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.reports.index": [],
    "panel.reports.exports.index": [],
    "panel.reports.exports.show": [
        {
            "name": "export",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.reports.export": [
        {
            "name": "report",
            "required": true
        }
    ],
    "panel.reports.show": [
        {
            "name": "report",
            "required": true
        }
    ],
    "panel.impersonate.enter": [
        {
            "name": "token",
            "required": true
        }
    ],
    "panel.impersonate.started": [],
    "panel.impersonate.leave": [],
    "panel.saas.subscription.index": [],
    "panel.saas.domains.index": [],
    "panel.saas.domains.store": [],
    "panel.saas.domains.verify": [
        {
            "name": "domain",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.saas.domains.primary": [
        {
            "name": "domain",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.saas.domains.destroy": [
        {
            "name": "domain",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.scheduling.index": [],
    "panel.scheduling.schedules.store": [],
    "panel.scheduling.schedules.update": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.scheduling.schedules.destroy": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.scheduling.overrides.store": [],
    "panel.scheduling.overrides.destroy": [
        {
            "name": "override",
            "required": true,
            "binding": "id"
        }
    ],
    "panel.scheduling.sessions.index": [],
    "panel.sessions.show": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.capacity": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.serials.store": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.call-next": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.start": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.pause": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.resume": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.close": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.cancel": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.delay": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.extend": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.transfer": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.pools.release-online": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.sessions.pools.split": [
        {
            "name": "session",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.check-in": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.call": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.start": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.complete": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.skip": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.return": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.no-show": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.reinstate": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.cancel": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.postpone": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.transfer": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.reorder": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.serials.priority": [
        {
            "name": "serial",
            "required": true,
            "binding": "public_id"
        }
    ],
    "panel.telemedicine.index": [],
    "panel.telemedicine.console": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "panel.telemedicine.start": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "panel.telemedicine.end": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "panel.telemedicine.token": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "panel.telemedicine.leave": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "panel.telemedicine.recording": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "panel.telemedicine.state": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "panel.telemedicine.quality": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "site.billing.checkout": [
        {
            "name": "appointment",
            "required": true,
            "binding": "public_id"
        }
    ],
    "site.billing.checkout.start": [
        {
            "name": "appointment",
            "required": true,
            "binding": "public_id"
        }
    ],
    "site.billing.callback": [
        {
            "name": "gateway",
            "required": true
        }
    ],
    "site.booking.index": [],
    "site.booking.kiosk": [],
    "site.booking.otp": [],
    "site.booking.store": [],
    "site.booking.confirmed": [
        {
            "name": "appointment",
            "required": true,
            "binding": "public_id"
        }
    ],
    "site.booking.doctor": [
        {
            "name": "doctor",
            "required": true
        }
    ],
    "site.home": [],
    "site.locale": [],
    "site.portal.login": [],
    "site.portal.otp.request": [],
    "site.portal.verify": [],
    "site.portal.otp.verify": [],
    "site.portal.home": [],
    "site.portal.acting_for": [],
    "site.portal.logout": [],
    "site.prescription.verify": [
        {
            "name": "code",
            "required": true
        }
    ],
    "site.prescription.verify.pdf": [
        {
            "name": "code",
            "required": true
        }
    ],
    "site.prescription.drug": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "site.queue.vanity": [
        {
            "name": "tenantHost",
            "required": true
        },
        {
            "name": "doctorSlug",
            "required": true
        }
    ],
    "site.queue.page": [
        {
            "name": "doctorSlug",
            "required": true
        }
    ],
    "site.queue.resolve": [
        {
            "name": "localId",
            "required": true
        }
    ],
    "site.queue.display": [
        {
            "name": "branchSlug",
            "required": true
        }
    ],
    "site.queue.state": [
        {
            "name": "doctorSlug",
            "required": true
        }
    ],
    "site.queue.sessions": [
        {
            "name": "doctorSlug",
            "required": true
        }
    ],
    "site.telemedicine.book": [],
    "site.telemedicine.book.store": [],
    "site.telemedicine.booked": [
        {
            "name": "appointment",
            "required": true,
            "binding": "public_id"
        }
    ],
    "site.telemedicine.join": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "site.telemedicine.room": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "site.telemedicine.room.state": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "site.telemedicine.room.token": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "site.telemedicine.room.leave": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ],
    "site.telemedicine.room.quality": [
        {
            "name": "room",
            "required": true,
            "binding": "room_name"
        }
    ]
}
}
export {};
